version: '3.8'
services:
  postgres_db:
    image: postgres:16.2
    container_name: rbaPostgres
    restart: always
    environment:
      POSTGRES_DB: creditcarddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      # Korist port 5433 da ne dolazi do sukoba sa postgresSQL postojecom instalacijom na Windowsu
      - "5433:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
volumes:
  postgres_db_data:
    driver: local
